name: Update CV

on:
  push:
    paths:
      - '.github/workflows/update-cv.yml'

permissions:
  contents: write

jobs:
  update-cv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Decode CV
        run: cat cv_chunks/part* | base64 -d > cv.pdf
      - name: Commit CV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cv.pdf
          git commit -m "Update CV" || exit 0
          git push
